version: "3.6"
services:
  web:
    build: .
    command: python3 manage.py migrate --noinput
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: "postgres:11-alpine"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
