# Generated by Django 2.1.1 on 2018-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20181029_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(default='Nairobi', max_length=20),
        ),
    ]
